stages:
- build_sh

variables:
  msName: $CI_PROJECT_NAME
  msPort: 11020
  
build_sh:
  stage: build_sh
  script:
  - sh /opt/dockerStackConfig/build.sh $msName $msPort $CI_PROJECT_DIR  $CI_PROJECT_PATH $CI_PROJECT_NAMESPACE $CI_COMMIT_REF_NAME
  tags:
  - shell
  when: manual